language: java
jdk: openjdk11

services:
  - rabbitmq
  - mysql

# Making that sure right mysql version is used
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_install:
  - mysql -u root -e 'CREATE DATABASE chess_online_dev;'

script:
  - ./mvnw clean integration-test