language: java
jdk: openjdk11

dist: bionic

services:
  - rabbitmq
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS chess_online_dev;'

script:
  - ./mvnw clean integration-test