language: java
jdk: openjdk11

services:
  - rabbitmq
  - mysql

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -e 'CREATE DATABASE chess_online_dev;'

script:
  - ./mvnw clean integration-test