spring:
  datasource:
    url: jdbc:mysql://localhost/chess_online_dev?useSSL=false&serverTimezone=Europe/Stockholm
    username: root
    password: password
  rabbitmq:
    host: localhost
    username: 'guest'
    password: 'guest'

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  tomcat:
    max-http-post-size: 10485760
  servlet:
    session:
      timeout: -1
logging:
  level:
    org:
      springframework: INFO
    com:
      company: DEBUG







