rooms: 20

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost/chess_online_dev?useSSL=false&serverTimezone=Europe/Stockholm
    username: root
    password: password

logging:
  level:
    org:
      springframework: INFO
    com:
      company: DEBUG